[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -std=gnu++17
monitor_speed = 115200

; Flashを16MBとしてフルに使う
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; N16R8のPSRAM (8MB) を有効化
board_build.arduino.memory_type = qio_opi
build_flags = 
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; LittleFS設定
board_build.filesystem = littlefs

; ライブラリ
lib_deps = 
    Links2004/WebSockets
